spring.application.name=resturantfunny
server.port=${PORT:8080}

spring.funny.config.supabase.url=${SUPABASE_URL}
spring.funny.config.supabase.apikey=${SUPABASE_API_KEY}
spring.funny.config.supabase.authorization=${SUPABASE_AUTHORIZATION}

# CRON JOB
spring.funny.config.cronjob.cron=${CRON_EXPRESSION:0 0 2 * * *}

logging.level.root=info
logging.charset.console=utf-8
logging.pattern.console=%d{dd MMM yyyy HH:mm:ss.SSS} [%X{uuid}] FUNNY %c[%M]: %p %m%n

spring.graphql.graphiql.enabled=true
