spring.application.name=resturantfunny
server.port={PORT}

spring.funny.config.supabase.url={SUPABASE_URL}
spring.funny.config.supabase.apikey={SUPABASE_API_KEY}
spring.funny.config.supabase.authorization={SUPABASE_AUTHORIZATION}

logging.level.root=info
logging.charset.console=utf-8
logging.pattern.console=%d{dd MMM yyyy HH:mm:ss.SSS} [%X{uuid}] FUNNY %c[%M]: %p %m%n
